export const parties = {
  "Vimal Exports": [],
  "Vishnu Laxmi": [],
  "Ujwal Textile mills": [],
  "Kundan Textile mills": [],
  "Mahak Creation": [],
  "Gayal Mata Textiles": [],
  "Suman Enterprises": [],
  "Satyam Synthetics": [],
  "LT Trade": [],
  "Lucky Enterprises": [],
  "RK fabrics": [],
  "Manish Textiles": [],
  "Balaji Textile Mills": [],
  "NN Creation": [],
  "Ramesh Rathi": [],
  "Ramdev Exports": [],
  "Veetrag Enterprises": [],
  "Jethmal Paliwal": [],
  "Manicot Fabrics": [],
  "Anuradha Fabrics": [],
  "Radhey Tex Fab": [],
  "JK Lungie": [],
  "Century Exports": [],
  "New Asia Textiles": [],
  "Ramalingam Textiles": [],
  "Harshika Exports": [],
  "Lakshmi Textiles": [],
  "Hanuman Tex Fab": [],
  "Shree Ganesh Mills": [],
  "Shri Ganapathi Textiles": [],
  "Sunrise Textiles": [],
  "Jain Co Exports": [],
  "Manoj Exports": [],
  "Sri Komal Cotton Mills": [],
  "RK Textiles": [],
  "Sree Ram Textiles": [],
  "Kamadhenu Textile Mills": [],
  "ME Textiles": [],
  "Mahaveer Cotton Mills": [],
  "Mehta Textile Mills": [],
};
